name: WorldEditSelectionVisualizer
main: com.rojel.wesv.WorldEditSelectionVisualizer
version: 1.4-dev
author: Rojetto
description: Shows WorldEdit selections with particles.
depend: [WorldEdit]
softdepend: [ProtocolLib]
commands:
  wesv:
    description: Toggles the WorldEditSelectionVisualizer.
    permission: wesv.toggle
    usage: /wesv
permissions:
  wesv.*:
    default: true
    children:
      wesv.use: true
      wesv.toggle: true
  wesv.use:
    default: true
    description: Allows the WESV to be on.
  wesv.toggle:
    default: true
    description: Allows you to toggle your WESV.